apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webserver.fullname" . }}-html
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
data:
  index.html: |
    <!doctype html>
    <html><head><title>Kubernetes Assignment</title></head>
    <body><h1>{{ .Values.candidate.name }}</h1><p>{{ .Values.candidate.architecture }}</p></body></html>
